spring:
  profiles:
    group:
      dev: dev, cmmn
      prod: prod, cmmn
---
spring:
  config:
    activate:
      on-profile: cmmn
  servlet:
    multipart:
      max-file-size: 50MB
mybatis:
  type-aliases-package: com.project.homepage
  mapper-locations: classpath:mapper/**/*.xml

rss:
  url: https://mytilblog.tistory.com/rss
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/homepage
    username: root
    password: 1234

server:
  port: 8001

file:
  path: C:/5224-homepage/
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.0.47:3307/homepage
    username: root
    password: agg8827

server:
  port: 80

file:
  path: /home/download/